// ============================================================
// packages-data.js — India Package Catalog (2-Night Gateways)
// ============================================================

const PACKAGE_CATALOG = {
    categories: ['2 Night Gateway'],
    regions: ['South India', 'North India', 'Himachal', 'Jammu & Kashmir', 'East India', 'West & Central'],

    packages: [
        // ── SOUTH INDIA ─────────────────────────────────────
        {
            id: 'munnar-2n',
            name: 'Munnar Escape',
            destination: 'Munnar',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Cochin', 'Kochi'],
            highlights: ['Tea plantation walks', 'Eravikulam National Park', 'Mattupetty Dam'],
            tags: ['hills', 'nature', 'couple', 'family'],
            bestSeason: 'Sep–May',
        },
        {
            id: 'goa-2n',
            name: 'Goa Sun & Sand',
            destination: 'Goa',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Goa', 'Mumbai', 'Bangalore'],
            highlights: ['Beach hopping', 'Old Goa Churches', 'Spice plantation tour'],
            tags: ['beach', 'leisure', 'couple', 'group'],
            bestSeason: 'Nov–Mar',
        },
        {
            id: 'coorg-2n',
            name: 'Coorg Coffee Trail',
            destination: 'Coorg',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Bangalore'],
            highlights: ['Coffee estate tour', 'Abbey Falls', 'Raja's Seat viewpoint'],
            tags: ['hills', 'nature', 'couple', 'family'],
            bestSeason: 'Oct–May',
        },
        {
            id: 'chikamangalur-2n',
            name: 'Chikmagalur Hills',
            destination: 'Chikmagalur',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Bangalore', 'Coimbatore'],
            highlights: ['Mullayangiri trek', 'Coffee plantations', 'Hebbe Falls'],
            tags: ['hills', 'trekking', 'couple', 'adventure'],
            bestSeason: 'Sep–Feb',
        },
        {
            id: 'ooty-2n',
            name: 'Ooty Nilgiri Hills',
            destination: 'Ooty',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Coimbatore', 'Bangalore', 'Chennai'],
            highlights: ['Toy train ride', 'Ooty Lake', 'Botanical Gardens'],
            tags: ['hills', 'family', 'couple', 'nature'],
            bestSeason: 'Mar–Jun, Sep–Nov',
        },
        {
            id: 'kovalam-2n',
            name: 'Kovalam Beach Retreat',
            destination: 'Kovalam',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Thiruvananthapuram', 'Trivandrum'],
            highlights: ['Lighthouse Beach', 'Ayurvedic spa', 'Sunrise at Hawa Beach'],
            tags: ['beach', 'wellness', 'couple', 'leisure'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'puducherry-2n',
            name: 'Pondicherry French Escape',
            destination: 'Puducherry',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Chennai', 'Puducherry'],
            highlights: ['French Quarter walk', 'Auroville', 'Promenade Beach'],
            tags: ['culture', 'beach', 'couple', 'heritage'],
            bestSeason: 'Oct–Feb',
        },
        {
            id: 'chennai-2n',
            name: 'Chennai City & Coast',
            destination: 'Chennai',
            category: '2 Night Gateway',
            region: 'South India',
            nights: 2,
            days: 3,
            departureCities: ['Chennai'],
            highlights: ['Marina Beach', 'Kapaleeshwarar Temple', 'Mahabalipuram day trip'],
            tags: ['city', 'culture', 'heritage', 'family'],
            bestSeason: 'Nov–Feb',
        },

        // ── NORTH INDIA ──────────────────────────────────────
        {
            id: 'delhi-2n',
            name: 'Delhi Heritage Trail',
            destination: 'Delhi',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Delhi'],
            highlights: ['Old Delhi bazaars', 'Red Fort & Qutub Minar', 'India Gate & Rajpath'],
            tags: ['city', 'heritage', 'culture', 'family'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'udaipur-2n',
            name: 'Udaipur City of Lakes',
            destination: 'Udaipur',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Udaipur', 'Jaipur'],
            highlights: ['Lake Pichola boat ride', 'City Palace', 'Vintage Car Museum'],
            tags: ['heritage', 'romance', 'couple', 'royal'],
            bestSeason: 'Sep–Mar',
        },
        {
            id: 'jaipur-2n',
            name: 'Jaipur Pink City',
            destination: 'Jaipur',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Jaipur'],
            highlights: ['Amber Fort', 'Hawa Mahal', 'Jantar Mantar'],
            tags: ['heritage', 'culture', 'family', 'royal'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'agra-2n',
            name: 'Agra Taj & Beyond',
            destination: 'Agra',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Delhi', 'Agra'],
            highlights: ['Taj Mahal sunrise', 'Agra Fort', 'Fatehpur Sikri'],
            tags: ['heritage', 'romance', 'couple', 'UNESCO'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'varanasi-2n',
            name: 'Varanasi Spiritual Trail',
            destination: 'Varanasi',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Varanasi'],
            highlights: ['Ganga Aarti at Dashashwamedh Ghat', 'Boat ride at sunrise', 'Sarnath'],
            tags: ['spiritual', 'culture', 'heritage', 'solo'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'ayodhya-2n',
            name: 'Ayodhya Sacred Journey',
            destination: 'Ayodhya',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Ayodhya', 'Lucknow'],
            highlights: ['Ram Mandir darshan', 'Saryu River Aarti', 'Hanuman Garhi'],
            tags: ['spiritual', 'pilgrimage', 'family'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'jaisalmer-2n',
            name: 'Jaisalmer Desert Camp',
            destination: 'Jaisalmer',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Jaisalmer', 'Jodhpur'],
            highlights: ['Sam Sand Dune camel safari', 'Jaisalmer Fort walk', 'Desert camp stargazing'],
            tags: ['adventure', 'desert', 'couple', 'unique'],
            bestSeason: 'Oct–Feb',
        },
        {
            id: 'ahmedabad-2n',
            name: 'Ahmedabad Heritage Walk',
            destination: 'Ahmedabad',
            category: '2 Night Gateway',
            region: 'North India',
            nights: 2,
            days: 3,
            departureCities: ['Ahmedabad', 'Jodhpur'],
            highlights: ['Sabarmati Ashram', 'Adalaj Stepwell', 'Calico Museum of Textiles'],
            tags: ['heritage', 'culture', 'UNESCO', 'family'],
            bestSeason: 'Oct–Mar',
        },

        // ── JAMMU & KASHMIR ──────────────────────────────────
        {
            id: 'srinagar-2n',
            name: 'Srinagar Dal Lake',
            destination: 'Srinagar',
            category: '2 Night Gateway',
            region: 'Jammu & Kashmir',
            nights: 2,
            days: 3,
            departureCities: ['Srinagar'],
            highlights: ['Houseboat stay on Dal Lake', 'Mughal Gardens', 'Shikara ride'],
            tags: ['romance', 'couple', 'nature', 'hills'],
            bestSeason: 'Apr–Oct',
        },
        {
            id: 'gulmarg-2n',
            name: 'Gulmarg Snow & Gondola',
            destination: 'Gulmarg',
            category: '2 Night Gateway',
            region: 'Jammu & Kashmir',
            nights: 2,
            days: 3,
            departureCities: ['Srinagar'],
            highlights: ['Gondola cable car ride', 'Skiing in winter', 'Apharwat Peak views'],
            tags: ['adventure', 'snow', 'couple', 'nature'],
            bestSeason: 'Dec–Mar (snow), May–Sep (greenery)',
        },

        // ── HIMACHAL PRADESH ─────────────────────────────────
        {
            id: 'shimla-2n',
            name: 'Shimla Queen of Hills',
            destination: 'Shimla',
            category: '2 Night Gateway',
            region: 'Himachal',
            nights: 2,
            days: 3,
            departureCities: ['Chandigarh'],
            highlights: ['The Mall Road walk', 'Jakhu Temple', 'Toy train (Kalka–Shimla)'],
            tags: ['hills', 'family', 'couple', 'snow'],
            bestSeason: 'Oct–Jun',
        },
        {
            id: 'manali-2n',
            name: 'Manali Valley Escape',
            destination: 'Manali',
            category: '2 Night Gateway',
            region: 'Himachal',
            nights: 2,
            days: 3,
            departureCities: ['Chandigarh'],
            highlights: ['Solang Valley snow activities', 'Hadimba Temple', 'Beas River rafting'],
            tags: ['adventure', 'nature', 'couple', 'honeymoon'],
            bestSeason: 'Oct–Jun',
        },
        {
            id: 'kasol-2n',
            name: 'Kasol Parvati Valley',
            destination: 'Kasol',
            category: '2 Night Gateway',
            region: 'Himachal',
            nights: 2,
            days: 3,
            departureCities: ['Chandigarh'],
            highlights: ['Kheerganga trek', 'Parvati River camps', 'Kasol village walk'],
            tags: ['trekking', 'adventure', 'backpacker', 'nature'],
            bestSeason: 'Mar–Jun, Sep–Nov',
        },

        // ── EAST INDIA ───────────────────────────────────────
        {
            id: 'darjeeling-2n',
            name: 'Darjeeling Tea & Himalayas',
            destination: 'Darjeeling',
            category: '2 Night Gateway',
            region: 'East India',
            nights: 2,
            days: 3,
            departureCities: ['Bagdogra'],
            highlights: ['Tiger Hill sunrise (Kanchenjunga view)', 'Tea garden tour', 'Toy train'],
            tags: ['hills', 'nature', 'family', 'couple'],
            bestSeason: 'Mar–May, Sep–Nov',
        },
        {
            id: 'gangtok-2n',
            name: 'Gangtok Sikkim Explorer',
            destination: 'Gangtok',
            category: '2 Night Gateway',
            region: 'East India',
            nights: 2,
            days: 3,
            departureCities: ['Bagdogra'],
            highlights: ['Tsomgo Lake', 'Rumtek Monastery', 'MG Marg walk'],
            tags: ['hills', 'culture', 'nature', 'family'],
            bestSeason: 'Mar–May, Oct–Dec',
        },
        {
            id: 'kolkata-2n',
            name: 'Kolkata City of Joy',
            destination: 'Kolkata',
            category: '2 Night Gateway',
            region: 'East India',
            nights: 2,
            days: 3,
            departureCities: ['Kolkata'],
            highlights: ['Victoria Memorial', 'Howrah Bridge walk', 'Park Street food tour'],
            tags: ['city', 'heritage', 'culture', 'food'],
            bestSeason: 'Oct–Feb',
        },

        // ── WEST & CENTRAL ───────────────────────────────────
        {
            id: 'mumbai-2n',
            name: 'Mumbai Maximum City',
            destination: 'Mumbai',
            category: '2 Night Gateway',
            region: 'West & Central',
            nights: 2,
            days: 3,
            departureCities: ['Mumbai'],
            highlights: ['Gateway of India', 'Marine Drive sunset', 'Dharavi & Dhobi Ghat tours'],
            tags: ['city', 'culture', 'food', 'heritage'],
            bestSeason: 'Nov–Feb',
        },
        {
            id: 'lonavala-2n',
            name: 'Lonavala Weekend Getaway',
            destination: 'Lonavala',
            category: '2 Night Gateway',
            region: 'West & Central',
            nights: 2,
            days: 3,
            departureCities: ['Mumbai', 'Pune'],
            highlights: ['Bhushi Dam', 'Tiger's Leap viewpoint', 'Karla & Bhaja Caves'],
            tags: ['hills', 'nature', 'family', 'couple'],
            bestSeason: 'Jun–Sep (monsoon), Nov–Feb',
        },
        {
            id: 'hyderabad-2n',
            name: 'Hyderabad Biryani & Bazaars',
            destination: 'Hyderabad',
            category: '2 Night Gateway',
            region: 'West & Central',
            nights: 2,
            days: 3,
            departureCities: ['Hyderabad'],
            highlights: ['Charminar & Laad Bazaar', 'Golconda Fort', 'Ramoji Film City'],
            tags: ['city', 'heritage', 'food', 'culture'],
            bestSeason: 'Oct–Mar',
        },
        {
            id: 'visakhapatnam-2n',
            name: 'Vizag Beach & Hills',
            destination: 'Visakhapatnam',
            category: '2 Night Gateway',
            region: 'West & Central',
            nights: 2,
            days: 3,
            departureCities: ['Visakhapatnam'],
            highlights: ['RK Beach & Kailasagiri', 'Borra Caves', 'Araku Valley coffee'],
            tags: ['beach', 'nature', 'hills', 'family'],
            bestSeason: 'Oct–Feb',
        },
    ]
};

// Helper — get unique departure cities across all packages
PACKAGE_CATALOG.allDepartureCities = [...new Set(
    PACKAGE_CATALOG.packages.flatMap(p => p.departureCities)
)].sort();
